# Generated by Django 3.2.13 on 2022-06-13 20:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='type_of_server',
            fields=[
                ('type_server_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('server_type', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='server',
            fields=[
                ('server_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('processor_number', models.CharField(max_length=45)),
                ('memory_capacity', models.CharField(max_length=45)),
                ('storage_capacity', models.CharField(max_length=45)),
                ('type_of_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_main.type_of_server')),
            ],
        ),
    ]
