# Generated by Django 3.2.13 on 2022-06-13 20:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crud_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=45)),
                ('sur_name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name_app', models.CharField(max_length=45)),
                ('logo_app', models.ImageField(blank=True, null=True, upload_to='')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_main.server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_main.user')),
            ],
        ),
    ]
