# Generated by Django 3.2.13 on 2022-06-13 20:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crud_main', '0002_application_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name_of_service', models.CharField(max_length=45)),
                ('date_of_launch', models.DateField()),
                ('memory_used', models.CharField(max_length=45)),
                ('ram_memory', models.CharField(max_length=45)),
                ('service_launched_onto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_main.server')),
            ],
        ),
    ]
