# Generated by Django 3.2.13 on 2022-06-13 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_main', '0003_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='applicaitonshasservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_main.application')),
                ('services_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_main.services')),
            ],
        ),
    ]
