# Generated by Django 3.2.13 on 2022-06-14 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_main', '0005_overall'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicaitonshasservices',
            options={'ordering': ['app_id'], 'verbose_name_plural': 'AppsHasService'},
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['name_app'], 'verbose_name_plural': 'Apps'},
        ),
        migrations.AlterModelOptions(
            name='overall',
            options={'ordering': ['number_of_server_used'], 'verbose_name_plural': 'Overall'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['name'], 'verbose_name_plural': 'Servers'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['service_id'], 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='type_of_server',
            options={'ordering': ['type_server_id'], 'verbose_name_plural': 'types_of_server'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['user_id'], 'verbose_name_plural': 'Users'},
        ),
    ]
